package com.pzque.coco.errors

class RuntimeError(message: String)
  extends Exception(s"RuntimeError: $message") {

  def this(message: String, cause: Throwable) {
    this(message)
    initCause(cause)
  }

  def this(cause: Throwable) {
    this(Option(cause).map(_.toString).orNull, cause)
  }

  def this() {
    this(null: String)
  }
}
